### ISSUE TITLE
Site is outdated

### ISSUE THREAD

**Issue by mj41** [sheriff/perl6status#3]
## Got:

What is the current status of Perl 6?
Quick answer: there's a usable alpha, ready to download and use right now.

Last updated: 2014-10-31
## Expected:

The July 2016 release of “Rakudo Star”, a useful and usable production distribution of Perl 6. 

This is the third post-Christmas (production) release of Rakudo Star and implements Perl v6.c. It comes with support for the MoarVM backend (all module tests pass on supported platforms).

http://rakudo.org/2016/07/22/announce-rakudo-star-release-2016-07/

**Comment by pjlsergeant** [comment]
Updated
